In [1]:
from tensorflow.keras.utils import to_categorical
import numpy as np

In [2]:
data = [15, 17, 5, 10, 0]
dat = np.array(data)
print(dat)

[15 17  5 10  0]


In [3]:
encoded = to_categorical(dat)
print(encoded)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [4]:
inverted = np.argmax(encoded[1])
print(inverted)

17
